version: '3.5'
services:
  postgres:
    image: postgres
    container_name: movie-store-postgres
    restart: always
    environment:
      POSTGRES_USER: db_movie_store
      POSTGRES_PASSWORD: kmasd812hnf87ds&vf$
    ports:
      - 5432:5432
    volumes:
      - ./15/data:/var/lib/postgresql/data
      - /dumps
  redis:
    container_name: movie-store-redis-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
    redis: