version: '3.5'
services:
  pgdb:
    image: postgres
    container_name: $(CONTAINER_NAME)
    restart: always
    environment:
      POSTGRES_USER: $(DB_NAME)
      POSTGRES_PASSWORD: $(DB_PASSWORD)
    ports:
      - 5432:5432
    volumes:
      - ./15/data:/var/lib/postgresql/data
      - /dumps